# roles/wordpress/tasks/install.yml
---

- name: Ensure repository is installed
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items: 
    - apache2
    - php7.3
    - php7.3-mysql
    - php7.3-curl
    - mariadb-client
    - nfs-common
    - cifs-utils

- name: Download WordPress
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Create devops if it does not exist
  become: yes
  file:
    path: /var/www/devops
    state: directory
    mode: '0755'    

- name: Create if it does not exist
  become: yes
  file:
    path: /var/www/devsec
    state: directory
    mode: '0755'

- name: Create devsecops if it does not exist
  become: yes
  file:
    path: /var/www/devsecops
    state: directory
    mode: '0755'

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/devops copy=no
  become: yes  

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/devsec copy=no
  become: yes  

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/devsecops copy=no
  become: yes  


