# roles/wordpress/tasks/install.yml
---
- name: Ensure repository is installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
    - apache2
    - libapache2-mod-php7.3 
    - php7.3 
    - php7.3-mysql 
    - php7.3-curl 
    - php7.3-json 
    - php7.3-gd 
    - php7.3-intl 
    - php7.3-sqlite3 
    - php7.3-gmp 
    - php7.3-mbstring 
    - php7.3-xml 
    - php7.3-zip
    - mariadb-client
    - nfs-common
    - cifs-utils

- name: Download WordPress
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Create devops if it does not exist
  become: yes
  file:
    path: /var/www/devops
    state: directory
    mode: '0755'    

- name: Create if it does not exist
  become: yes
  file:
    path: /var/www/devsec
    state: directory
    mode: '0755'

- name: Create devsecops if it does not exist
  become: yes
  file:
    path: /var/www/devsecops
    state: directory
    mode: '0755'

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/devops copy=no
  become: yes  

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/devsec copy=no
  become: yes  

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/devsecops copy=no
  become: yes  

- name: Ensure correct permissions
  become: yes
  file:
    path: "/var/www"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
